exception: fix exceptions thrown from C++ not being catched
This is because C++ code sees di_object with a different name:
::deai::c_api::di_object, but the old exception.cc code is trying to
catch ::di_object. Only those thrown via `di_throw` (also in
exception.cc) are catchable.

Make sure exception.cc uses the C++ type name as well.

Signed-off-by: Yuxuan Shui <yshuiv7@gmail.com>